### ISSUE TITLE
new datauri fails on windows

### ISSUE THREAD

**Issue by petero-dk** [rse/node-inline-assets#13]
On version 1.4.6 I get the following error

```
TypeError: (intermediate value).format is not a function
    at inlineAssetsForData (C:\Users\peter\AppData\Roaming\npm\node_modules\inline-assets\lib\inline-assets.js:116:31)
    at C:\Users\peter\AppData\Roaming\npm\node_modules\inline-assets\lib\inline-assets.js:256:28
    at String.replace (<anonymous>)
    at inlineAssetsForHTML (C:\Users\peter\AppData\Roaming\npm\node_modules\inline-assets\lib\inline-assets.js:248:23)
    at inlineAssets (C:\Users\peter\AppData\Roaming\npm\node_modules\inline-assets\lib\inline-assets.js:293:16)
    at Object.<anonymous> (C:\Users\peter\AppData\Roaming\npm\node_modules\inline-assets\bin\inline-assets.js:104:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

when I have the following code in my html

```
        <img src="images/logo.png" />
```

**Comment by rse** [comment]
Now fixed in version 1.4.7
